#!/usr/bin/env python3
"""Load a completed run artifact and generate byte-level text."""

from __future__ import annotations

import argparse

import jax
import jax.numpy as jnp

from megalodon_enwik8_jax.utils import (
    assert_trainable_dtype,
    count_trainable_params,
    decode_tokens,
    encode_prompt,
    generate,
    load_model_artifact,
    make_trainable_mask,
)


def main() -> None:
    """Run generation from a completed model artifact."""
    parser = argparse.ArgumentParser(
        description="Generate text from a completed experiment run",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--run-dir", required=True, help="Completed run directory")
    parser.add_argument("--prompt", default="The ", help="UTF-8 prompt")
    parser.add_argument("--max-new-tokens", type=int, default=128)
    parser.add_argument("--temperature", type=float, default=1.0)
    parser.add_argument("--top-k", type=int)
    parser.add_argument("--top-p", type=float)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    key = jax.random.PRNGKey(args.seed)
    key, load_key, generation_key = jax.random.split(key, 3)
    model, cfg = load_model_artifact(args.run_dir, load_key)
    trainable_mask = make_trainable_mask(model)
    if cfg["model"] == "llama":
        assert_trainable_dtype(model, jnp.float32, trainable_mask)
    parameter_count = count_trainable_params(model, trainable_mask)

    prompt_ids = encode_prompt(args.prompt)
    generated, _, _ = generate(
        model,
        prompt_ids,
        max_new_tokens=args.max_new_tokens,
        temperature=args.temperature,
        top_k=args.top_k,
        top_p=args.top_p,
        key=generation_key,
    )
    continuation = decode_tokens(generated[0, prompt_ids.shape[1] :])

    print(f"Model: {cfg['model']} ({parameter_count:,} parameters)")
    print(f"Prompt: {args.prompt!r}")
    print(f"Generated bytes decoded as UTF-8: {continuation!r}")
    print(f"Full output: {(args.prompt + continuation)!r}")


if __name__ == "__main__":
    main()
